export enum ErrorCodesEnum {
  REQUEST_ERROR = -1,
  ARRAY_ERROR = 0,
  GENERAL = 1,
  DATABASE = 2,
  VALIDATION = 3,
  NOT_FOUND = 4,
  ALREADY_DELETED = 5,
  GUID_CHANGED = 12,
  UNAUTHORIZED = 101,
  FORBID = 102
}
