export class BookmarkIcon {
  static dashboard = null;
  static commissionList = null;
  static commissionDetails = null;
  static departmentList = null;
  static departmentDetails = null;
  static academicDegreeList = null;
  static academicDegreeDetails = null;
  static academicTitleList = null;
  static academicTitleDetails = null;
  static teachingRankList = null;
  static teachingRankDetails = null;
  static teacherList = null;
  static teacherDetails = null;
  static educationQualificationList = null;
  static educationQualificationDetails = null;
  static educationList = null;
  static educationDetails = null;
}
